backend:
  name: github
  repo: invmv/invmv.github.io
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://invmy.us.kg
  auth_endpoint: /api/auth
media_folder: static/img
public_folder: /img
collections:
  # 页面集合
  - name: "pages"
    label: "页面"
    folder: "content"
    create: true
    slug: "{{slug}}/index"
    filter:
      - field: "type"
        value: "page"
    fields:
      - name: "title"
        label: "标题"
        widget: "string"
      - name: "toc"
        label: "目录"
        widget: "boolean"
        default: false
      - name: "description"
        label: "描述"
        widget: "text"
      - name: "layout"
        label: "布局"
        widget: "string"
        default: "default"
      - name: "body"
        label: "正文"
        widget: "markdown"
        editor_components: [] # 禁用内置组件
        buttons: ["bold", "italic", "link", "code", "heading-one", "heading-two", "heading-three"] # 显示工具栏按钮
        modes: ["raw", "rich_text"] # 支持 Markdown 视图与原始视图切换

  # 博客集合
  - name: "blog"
    label: "博客"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "标题"
        widget: "string"
      - name: "date"
        label: "发布日期"
        widget: "datetime"
      - name: "authors"
        label: "作者"
        widget: "list"
        fields:
          - name: "name"
            label: "姓名"
            widget: "string"
          - name: "image"
            label: "头像"
            widget: "hidden"
          - name: "link"
            label: "link"
            widget: "hidden"
      - name: "tags"
        label: "标签"
        widget: "list"
      - name: "excludeSearch"
        label: "排除搜索"
        widget: "boolean"
        default: false
      - name: "body"
        label: "正文"
        widget: "markdown"
        editor_components: [] # 禁用内置组件
        buttons: ["bold", "italic", "link", "code", "heading-one", "heading-two", "heading-three"] # 显示工具栏按钮
        modes: ["raw", "rich_text"] # 支持 Markdown 视图与原始视图切换

  # 文档集合
  - name: "docs"
    label: "文档"
    folder: "content/docs"
    create: true
    nested: # 修正为正确格式的对象
      depth: 100 # 如果需要嵌套目录支持
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "标题"
        widget: "string"
      - name: "weight"
        label: "权重"
        widget: "number"
        required: false
      - name: "next"
        label: "下一页"
        widget: "string"
        required: false
      - name: "prev"
        label: "上一页"
        widget: "string"
        required: false
      - name: "body"
        label: "正文"
        widget: "markdown"
        editor_components: [] # 禁用内置组件
        buttons: ["bold", "italic", "link", "code", "heading-one", "heading-two", "heading-three"] # 显示工具栏按钮
        modes: ["raw", "rich_text"] # 支持 Markdown 视图与原始视图切换

  # 博客索引页
  - name: "blog_index"
    label: "博客索引"
    files: # 用 files 配置单个文件
      - label: "博客索引"
        name: "blog_index"
        file: "content/blog/_index.md"
        fields:
          - name: "title"
            label: "标题"
            widget: "string"
          - name: "body"
            label: "正文"
            widget: "markdown"
            editor_components: [] # 禁用内置组件
            buttons: ["bold", "italic", "link", "code", "heading-one", "heading-two", "heading-three"] # 显示工具栏按钮
            modes: ["raw", "rich_text"] # 支持 Markdown 视图与原始视图切换

  # 文档索引页
  - name: "docs_index"
    label: "文档索引"
    files: # 用 files 配置单个文件
      - label: "文档索引"
        name: "docs_index"
        file: "content/docs/_index.md"
        fields:
          - name: "title"
            label: "标题"
            widget: "string"
          - name: "linkTitle"
            label: "链接标题"
            widget: "string"
          - name: "body"
            label: "正文"
            widget: "markdown"
            editor_components: [] # 禁用内置组件
            buttons: ["bold", "italic", "link", "code", "heading-one", "heading-two", "heading-three"] # 显示工具栏按钮
            modes: ["raw", "rich_text"] # 支持 Markdown 视图与原始视图切换